### PR TITLE
US24 (to be used in the future)

### PR DESCRIPTION
**Pull request by sanguinariojoe**
The fornt MG is not working... I took a look and the Stuart front MG does not works neither

### CODE REVIEW

**Comment by yuritch** [comment]
The unitdef does not include frontal MG at all. Is that what you meant by it not working? Because that's very easy to fix :)

**Comment by sanguinariojoe** [comment]
Is it not [this](https://github.com/spring1944/spring1944/pull/432/files#diff-5c974ce7bc27178c6910edfc83cd2b23eb910ed0ea3aac21e2b4bb9f93b59f43R21)?

I am not really the expert on UnitDefs... You and @jal76 are

**Comment by yuritch** [comment]
That's the coaxial MG - the one on the turret, right next to the cannon.

**Comment by sanguinariojoe** [comment]
How should look the UnitDef?

**Comment by yuritch** [comment]
Weapon 4 should be the frontal MG with a limited arc, weapon 5 the bulletproof effect. You can take a look at the T-34 unitdef - it has a similar setup.
Sherman tank is not a good example here as it also has an AA machinegun, which M24 has not.

**Comment by sanguinariojoe** [comment]
It seems to work! Thanks!

**Pull request merged**
