### PR TITLE
Capturable guns

### PR DESCRIPTION
**Pull request by sanguinariojoe**
A new system for guns!!! For the time being is just affecting the former infantry guns:

 - GBRParaM8Gun
 - GERleIG18
 - ITACannone65
 - USM8Gun

Now the guns have a crew, which can be unloaded and killed. Along this line, the new guns are filled with pistol guys. If killed/unloaded, those default crew members can be replaced by any infantry unit.

If a gun losses part of its crew, then it becomes inoperative until they are replaced.

If a gun looses all its crew members it can be captured. Moreover, the gun is turning neutral, so enemy units are not destroying it unless they are specifically asked to. If right click is used to "attack" the abandoned gun, all infantry units capable of capture it will do that.

The plan is extending this gun functionality for all other guns, including field guns, at and artillery. Those guns would deploy as they are doing now (as long as they have the full crew). Deployed guns strength will be increased and the crew members will be safe. The guns will not be created with a truck though.

A bit outdated footage can be found [here](https://www.youtube.com/watch?v=1HM0U4PcCDM).

### CODE REVIEW

**Comment by yuritch** [comment]
This is great!
It should also include the deployed machineguns at some point.
Not merging just yet as I haven't had a chance to test it.

**Comment by yuritch** [comment]
Some issues I found:
- infantry (rifles in this case) does not want to attack a manned gun, they just stand there and stare at it. Anti-tank rifles, however, shoot it. As if it was an armored vehicle.
- if a gun's crew is killed (by HE splash in this case), the gun correctly becomes non-hostile. However, none of the infantry units seem to be able to capture it. Right clicking produces the same result as above - infantry stands at max range and stares at the gun, doing nothing.
This was done using skirmish mode, engine 104.0.1-1553

**Comment by sanguinariojoe** [comment]
After debugging a bit I realized it was because the unit was never claiming to be "in building stance". It is so far related to this old issue:

https://github.com/spring1944/spring1944/issues/200

However, in this case the problem is a bit deeper, because if the unit is moving when the engine asks to start capturing, then it will give up, and never try again...

Now should works fine!

**Comment by yuritch** [comment]
I tested again and now it works fine.

**Comment by FLOZi** [comment]
Very cool.

Not sure if it would be worthwhile integrating gun shields with the armour hitbox system.

**Pull request merged**
