### PR TITLE
Allow C.R.A.I.G. to use advanced units

### PR DESCRIPTION
**Pull request by Lowdive**
-Created AI exclusive engineer for all factions except SWE and ITA (which already had one)
-Updated build order with advanced factories and units for US, GER, GBR, RUS, and JPN (though having issues with JPN); I overlooked ITA since it seems to have an updated buildorder already.
-Fixed AI spawn ITA and JPN AT guns (they are now stationary).

*all updated buildorders were tested once at least, AI vs. AI, not a perfect balance but at least it's not game-breaking... it appears.

### CODE REVIEW

**Comment by Lowdive** [comment]
my problem with japan is that it has some weird factory names that I cannot link to the build order... :question:

**Comment by ashdnazg** [comment]
Example?

**Comment by kanatohodets** [comment]
@Lowdive: cool, thanks for improving CRAIG! Would you mind cleaning up these commits a bit with rebase? Ideally this would collapse down to one single commit, I think.

**Comment by Lowdive** [comment]
@kanatohodets I'll see about that rebase.
@ashdnazg jpntankyard_medium, jpntankyard_support, jpnvehyard_landing, jpnvehyard_tank, jpnatyard
at some unitdef translator they get properly read as jpntankyard1-2, jpnvehicleyard1-2, jpnspyard1
but if I declare them like that in buildorder they have no buildmenu options, and if I declare them like tankyard_medium they throw errors of bad unit name.

**Comment by FLOZi** [comment]
Thought I made the names more consistent in sweden branch, :(

**Pull request closed without merging**
