### PR TITLE
Loading process optimization

### PR DESCRIPTION
**Pull request by sanguinariojoe**
A fix to https://github.com/spring1944/spring1944/issues/231

Comments:

- In an old computer, the global loading time has been reduced from 70 seconds to 40 seconds (almost 30 seconds are not associated with LuaRules)
- The LuaRules loading is crashing much less, even non-crashing in modern CPUs
- All the autogenerated models have not the normaltex attribute yet.
- I did my best to preserve the normaltex attributes, but probably I made mistakes. **Testing is required!**
- Of course this patch has not effect if LUA shaders are not enabled

### CODE REVIEW

**Comment by ashdnazg** [comment]
all the ```normaltex			= "",``` seem like they could either be removed, be inherited from somewhere or added in _post

**Comment by ashdnazg** [comment]
also, I think a better approach will be to make a python script that goes through the models and outputs a normals_def.lua file which is then used wherever it's needed.

**Comment by PepeAmpere** [comment]
As I mentioned already in chat, the loading crashes can be prevented by launching the -safemode as starting parameter, but it was only hot-fix solution for me. If this branch is solving all the invalid content and configs, its great. The load takes few seconds once fixed.

**Comment by sanguinariojoe** [comment]
> all the `normaltex = ""`, seem like they could either be removed, be inherited from somewhere or added in _post
> also, I think a better approach will be to make a python script that goes through the models and outputs a normals_def.lua file which is then used wherever it's needed.

I already though that, but in S:44 there are dozens of edge cases (units and features defined in LUA tables, in legacy mode, as inherited classes, and autogenerated by name reference), at a point that making it by hand is very competitive in front of generating some sort of script or workaround.
So I guess this approach is the most sensible fix right now. Maybe not the smartest one anyway...

> As I mentioned already in chat, the loading crashes can be prevented by launching the `-safemode` as starting parameter, but it was only hot-fix solution for me. If this branch is solving all the invalid content and configs, its great. The load takes few seconds once fixed.

`-safemode` is disabling LUA shaders, that's why it's working like a charm. Of course then you are loosing advance shading features
This patch is only fixing the loading process, but not the shaders incorrect uniform variables warnings.

**Pull request merged**
