### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Reducing the repo size:

* Moving README to the wiki
* Removing houses stuff, already covered by houses feature pack

### CODE REVIEW

**Comment by PepeAmpere** [comment]
Good we remove that to separate package, but I consider adding it into repo just for few months as mistake, which increased size of our repo by hundreds of MB forever. Please consider adding any content (big binary files) into this repo in the future, esp. if procedurally created.

**Comment by sanguinariojoe** [comment]
You right... I badly planned it

**Comment by PepeAmpere** [comment]
@yuritch can you perform rebase & squash & merge instead of simple merge once you finishing the pull request? I talked about that with you and @sanguinariojoe (i hope with both) that it is producing unnecessary branches in dev graph from historic point of view. Sometimes the simple merge is better solution (e.g. in case of my very old branch) but for upgrades which takes few commits in week period we should squash whole upgrade to one commit, rebase it and then merge it.

**Comment by PepeAmpere** [comment]
btw the github UI offers you this alternative

**Comment by sanguinariojoe** [comment]
+1

**Pull request merged**
