### PR TITLE
Let's use the Balanced Annihilation chat widget

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Not much else to say

### CODE REVIEW

**Comment by ashdnazg** [comment]
please don't add redui.
We've added chili for a reason.

**Comment by specing** [comment]
I believe the ZK chat widget is the best one for copy&paste (it is Chilli).

**Comment by ashdnazg** [comment]
indeed

**Comment by sanguinariojoe** [comment]
I also prefer chili! I added this one because someone suggested that

**Pull request closed without merging**
