### PR TITLE
SpringBoard

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Sometimes both, the number of teams and the teams IDs may change, e.g. when loading a project with [SpringBoard](https://github.com/Spring-SpringBoard/SpringBoard-Core).

### CODE REVIEW

**Comment by ashdnazg** [comment]
put ```local teams = Spring.GetTeamList()``` outside the for loop.

**Comment by sanguinariojoe** [comment]
No way, As I said, that can be required to be updated after game started. Example given, loading project with SpringBoard.

IDEM for loops

**Comment by ashdnazg** [comment]
please read my reply again

**Comment by sanguinariojoe** [comment]
Oh! yes! You are totally right!

**Comment by ashdnazg** [comment]
last commit probably in the wrong branch?

**Comment by sanguinariojoe** [comment]
Actually no... It is a branch to adapt S44 to SpringBoard. In fact the PR is wrong (I already changed the title).

**Comment by ashdnazg** [comment]
ah, ok!

**Pull request merged**
