### PR TITLE
New UI (and some lobby integration details)

### PR DESCRIPTION
**Pull request by sanguinariojoe**
A new UI. A lot of testing will be required...

Potential benefits:

* No additional Chili instances
* Significantly simpler than NOTA UI, specially at the time of handling events. That should make it more robust.
* No git submodules required anymore
* Better look & feel
* It will eventually work with the coming in-game lobby

### CODE REVIEW

**Comment by Lowdive** [comment]
will test ASAP

**Comment by buumi** [comment]
Console crash when writing message
```
[f=0013436] [widgets.lua] Error: false
[f=0013436] [widgets.lua] Error: Error in AddConsoleLine(): [string "LuaUI/Widgets/gui_s44_console.lua"]:230: attempt to index local 'color' (a nil value)
[f=0013436] [widgets.lua] Error: Removed widget: 1944 Console
```

Resign button didn't do anything for me.

Some text is a bit hard to read: for example build scout plane from German HQ. That number 1 is hard to distinguish from background.

**Comment by sanguinariojoe** [comment]
> Console crash when writing message

[I have implemented a fallback color selector](https://github.com/spring1944/spring1944/pull/368/commits/bdc8a2fe1a22a7e1f54ec659e77da56c58146868). Not a ideal solution, but shall do the job

> Resign button didn't do anything for me.

AFAIK resign button works just fine. However, if you tested the system without any enemy AI, the game will not finish after you resign because of the [game_end.lua gadget](https://github.com/spring1944/spring1944/blob/master/LuaRules/Gadgets/game_end.lua#L475).

> Some text is a bit hard to read: for example build scout plane from German HQ. That number 1 is hard to distinguish from background.

[I enlarged them to better fit the available space](https://github.com/spring1944/spring1944/pull/368/commits/9a314afcae2aa27b31ea4bea0bbba91dcb88f320).

**Comment by buumi** [comment]
Ok, that explains my resign issue then. Font is better for me now, also locking works nice. And chat doesn't crash anymore.

I actually preferred the old selection boxes at the bottom of screen instead of on right side. It's ok to me if I have to bring those back manually but you might want to check with others what's their opinion.

**Comment by sanguinariojoe** [comment]
> I actually preferred the old selection boxes at the bottom of screen instead of on right side

I rather keep them at right side, for 2 reasons:

* Screens horizontal scale is significantly larger than vertical one, so in general is a good idea to try to fill the sides
* Chat should be an horizontal widget, a large one actually, so it should be placed at bottom

> I kind of like the effect of easily noticing someone is speaking when they appear to eye sight
> static always visible makes it easier to miss it

OK, I can implement a fade effect (I hope so...)

**Comment by sanguinariojoe** [comment]
Perfect, now the message nicely fade away after 10 seconds

**Comment by sanguinariojoe** [comment]
I think I have the @buumi approval.

It would be great if @specing and @yuritch can take a look and eventually merge, so the real testing/fixing stage can begins

**Comment by jal76** [comment]
I want

**Comment by sanguinariojoe** [comment]
Uuuuh!!! bugs incoming, be prepared! I'll fix everything!

**Pull request merged**
