### PR TITLE
Upgraded the profiler

### PR DESCRIPTION
**Pull request by sanguinariojoe**
I just took the profiler from Zero-K.

* Widgets profiling can be enabled/disabled by F11 menu (`Widget Profiler New`)
* Gadgets profiling can be enabled typing in the chat `/luarules profile` and disabled typing `/luarules kill_profiler`

### CODE REVIEW

**Comment by Lowdive** [comment]
Did I hear my name? x'D

**Comment by Lowdive** [comment]
Seriously now, does this mean I can try the profiler now and maybe it will tell me what's bogging down my framerate?

**Comment by sanguinariojoe** [comment]
Hopefully!

**Comment by Lowdive** [comment]
> Hopefully!

Alright I'll check it out as soon as possible, after work.

**Comment by sanguinariojoe** [comment]
It's not merged yet...

Do you know how to download and test that?

**Comment by Lowdive** [comment]
Ah, I missed that fact, yeh I know how to, but I hope it can get merged somewhere along today before evening.

**Comment by Lowdive** [comment]
> 
> 
> Hopefully!

[f=0006589] start profiling (synced)
[f=0006589] hooked all callins
[f=0006589] hooked UpdateCallin

and nothing comes up afterwards, it's silent.

**Comment by sanguinariojoe** [comment]
Hey!

The profiler can only work on spring-104. If you used 103, you probably can find a line like that in your log:

`[f=-000001] Error: Failed to load: dbg_gadget_profiler_new.lua  ([string "LuaRules/Gadgets/dbg_gadget_profiler_new.lu..."]:384: attempt to call local 'spGetLuaMemUsage' (a nil value))`

**Comment by sanguinariojoe** [comment]
On top of that, to enable gadgets profiling you need 2 commands (my bad):

```
/luarules profile
/luarules uprofile
```

There are some other commands you can type:

```
    gadgetHandler.actionHandler.AddChatAction(gadget, 'uprofile', Start, " : starts the gadget profiler (for debugging issues)")
    gadgetHandler.actionHandler.AddChatAction(gadget, 'profile', StartSYNCED,"")
    gadgetHandler.actionHandler.AddChatAction(gadget, 'ap', StartBoth,"")
    gadgetHandler.actionHandler.AddChatAction(gadget, 'fprofile', FilterLowValueToggle," : filter out low values")
    gadgetHandler.actionHandler.AddChatAction(gadget, 'profilegadget', ToggleTargetGadget," : profilegadget <gadget_name> <how_much_second_to_profile>.")
```

**Pull request merged**
