### PR TITLE
Wiki widget

### PR DESCRIPTION
**Pull request by sanguinariojoe**
The widget to autogenerate the wiki units documentation:

https://gitlab.com/Spring1944/spring1944/wikis/factions/main

### CODE REVIEW

**Comment by Lowdive** [comment]
Beautiful

**Comment by sanguinariojoe** [comment]
Thanks ;-)

**Comment by Lowdive** [comment]
A catch to the autodoc procedure is the spawner units like the APMine, ATMine, GBR Glider, US Paradrop...
the only surprise is the GBR commando flare, I thought it would also have this lack of information but it does display the commando squad as a "Transformation".

**Comment by sanguinariojoe** [comment]
Yeah, there are some units documentation pending...

The GBR commando landing zone is in fact a transformation. See `LuaRules/Configs/side_morph_defs/gbr.lua`. Maybe it can be considered a bug. Would you open an issue?

**Comment by Lowdive** [comment]
What could be considered a bug? the transforming behavior or the spawner units? I would think you meant the latter but I'm unsure.

**Comment by sanguinariojoe** [comment]
Yes! That's the commando landing zone, right?

**Comment by Lowdive** [comment]
Ah, then, I didn't make myself clear, commando landing zone is fine, it does display its transformation properly in wiki.
It's the other units that will need aditional treatment (apmine, atmine, etc.)

**Comment by sanguinariojoe** [comment]
I personally wanna get the wiki merged in its current state to allow people eventually start documenting special units (a custom attribute called wiki_comments can be added to the units definitions). Also I wanna add an entry on the wiki about how to autogenerate the wiki

**Comment by Lowdive** [comment]
Yes that seems to be the only solution for special units like those.

**Comment by PepeAmpere** [comment]
@sanguinariojoe I have one practical comment to this merge: Can you perform squash before you merge branch? I know it is big piece of work and you want to capture your history of work but from long term perspective what is more important is tractability of the merge (=diff of that final commit and dev branch), not signle dev commits. From long term perspective it is not important in which order you implemented each doc file and which order you fixed some bugs. I was reading through your commits and I think If you would squashed all into one commit, it would be enough and much better.

**Comment by PepeAmpere** [comment]
Anyway still great job.

**Comment by sanguinariojoe** [comment]
> Can you perform squash before you merge branch?

I understand the point of squashing before merge, and in fact I'm quite agree with your arguments. However, I still prefer not squashing (I'm condemned to an endless schizophrenia :-) ). Is quite usual that the branch history contains really valuable information, like how to extend the features implemented, or even non-trivial bugs detected and fixed, which may easily become a regression in the future if squashed.

Summarizing, we have been working without squashing, and I would still doing that. But if the community decide to start squashing, I'll not oppose at all.

**Comment by PepeAmpere** [comment]
Practically after one year probability of someone digging in your unfinished-feature commits is very small. On the other hand if someone after three years wants identify the regression (who introduced the bug), its far more useful to have one squashed commits where you have final full contribution of given person (and clear changelog) instead of digging in 20 commits.

I understand you, I was opposing such "historic reversion" as well, but my more experienced colleagues convinced me and after many years working on more than ten years old repos it is really much more useful.

Also the second suggestion is to rebase before you squash, so the there are no parallel branches in our repository history. Good thing is that github supports it natively by UI, so you don't need to perform rebasing yourself in most of the cases.

**Comment by sanguinariojoe** [comment]
As I said, If the community would move to a squash based merging system, I will not oppose at all. But in such a case everyone shall do that. What I don't want is a salad of squashed and non-squashed commits.

Regarding rebasing, you are right! I'm just lazy... :-) I'll try to force myself to do that!

**Comment by PepeAmpere** [comment]
What salad? squashed commits appears to anyone else like ONE commit. Its like you would just commit all at once. Which some people do. Thats the point and also the advantage of it. If you agree with the advantages, you don't need to wait for "community" to start to do things better, right?

**Comment by sanguinariojoe** [comment]
Yes, I do

When someone is reading a repo history, is better to get a standardized behaviour (big monolithic commits or small dev history). The salad is when everything is mixed, and you never know what to expect

**Comment by PepeAmpere** [comment]
For me the criteria is not size of the commit, but completeness of the given feature, improving the project/product. 

* If I add new command to unit by one line change, it is supposed to be one separate commit
* If I add lua based system emulating old engine fuel behavior of airplanes which consist around 20 files and complex integration, it is supposed to be one commit as well, because the partial commits I used during the development were not adding anything to project, just the final commit/merge did it.
* If I develop auto-doc system for project, its possible to split it into separate commits for each section I implement each in one file - that makes sense. But it does not make sense to keep other 5 commits fixing some typos or mistakes in those files or development commits of the common core of the autodoc system.

So, If you bring the question "what to expect", my answer is: in new commit i expect something "finished" which is adding any value to the project. Any commits which are not producing improvements on the final project (=user has no new options, bug is still not fixed, functions are not refactored) are not important enough to be kept. That's the criteria.

**Comment by sanguinariojoe** [comment]
Let me say you I'm not interested on making such a planning on my PRs. Not yet.

Pepe, be realistic, we have 3 active devs. Indeed we need every single person-second available invested in deving.

We'll have hundreds of devs (probably in a couple of weeks :-) ), and then we'll need to carefully think on how to handle all the info. But for the time being the very only two methodologies I'm accepting are:

* Squashed single-commit PRs
* PRs like this one

This PR is closed to me

**Comment by PepeAmpere** [comment]
Maybe the issue is caused by fact you control git via command line - in such case squashing is pain. Im using SourceTree and its matter of few clicks.

Btw this has nothing to do with interest/not interest of doing that. There are other arguments (like size of the repository), time needed to overiview last changes.

I bring this topic because the Steam release is closer and any kind of improvement on dev-side which costs dev few seconds is worth of consider if it helps me a lot for making new stable releases.

For sure this merge is over, I just wanted to discuss without fights what we can do better in next months :)

**Pull request merged**
