### PR TITLE
suppressed prone soldiers hitsphere

### PR DESCRIPTION
**Pull request by PepeAmpere**
suppressed prone soldiers hitsphere [https://trello.com/c/SrskfX28/]

* suppressed prone soldiers have hitsphere lowered
* gets back once the suppression ends
* not applied on static units which can be suppressed (mg-nests, AA/AT guns)
* aiming position do not change (gameplay and technical reasons)

check results: https://youtu.be/t5zxxtRe-OA

### CODE REVIEW

**Comment by PepeAmpere** [comment]
ℹ️ "rebase and merge" please, if the pull request is approved

**Comment by sanguinariojoe** [comment]
Memory leak when units die?

As far as I can see, the units are removed from the table when unsupressed. Is that happening when destroyed as well?

**Comment by PepeAmpere** [comment]
true, fixed in a following commit

**Comment by sanguinariojoe** [comment]
I'm happy! (I have not tested that, but it seems pepe already did, and the stuff seems pretty robust)

**Pull request merged**
