### PR TITLE
Some fixes for 104+ engine version

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Some minor but convenient fixes for 104 and one critical for 104.0.1 (development version)

### CODE REVIEW

**Comment by yuritch** [comment]
Will this still be compatible with 103?

**Comment by sanguinariojoe** [comment]
Yes! By design! Anyway I already tested that

**Comment by sanguinariojoe** [comment]
WAIT! DON'T MERGE YET!
Errors detected...

**Comment by sanguinariojoe** [comment]
Here we go!

On top of that, I significantly reduced the consumed memory (~160MB in Moro River)

**Pull request merged**
