### PR TITLE
aimpoint moves down during the suppression and back 

### PR DESCRIPTION
**Pull request by PepeAmpere**
[https://trello.com/c/SrskfX28/]

### CODE REVIEW

**Comment by buumi** [comment]
I'm not well versed in spring programming but change looks ok to me. Just indentation is borked in if statement according to github.

**Comment by PepeAmpere** [comment]
@jal76 @buumi @sanguinariojoe after two positive reviews I go forward. I will try to do squash before rebase and merge, which can do something unprectictible in this merge request. So be aware ;)

**Comment by PepeAmpere** [comment]
@buumi @jal76 @yuritch @sanguinariojoe looks fine - so guys it is possible to do 
* squash (interactive rebase) on your machine locally, 
* force-push your change back here and 
* then do "rebase-merge" via github UI 

and github handles it properly

**Comment by sanguinariojoe** [comment]
Sincer you have manually rebased, the third point is irrelevant, right? I mean, you can use "merge" and will get the same result... Am I wrong?

**Comment by PepeAmpere** [comment]
@sanguinariojoe You are right unless meanwhile someone else commit/merge something else to the master. Then it will produced unwanted merge commit.

**Comment by sanguinariojoe** [comment]
OK!

**Pull request merged**
