### PR TITLE
Try fix unlimited ammo for tanks (#308)

### PR DESCRIPTION
**Pull request by buumi**

### CODE REVIEW

**Comment by sanguinariojoe** [comment]
It seems OK to me!

**Comment by PepeAmpere** [comment]
It is NOT ok, it is workaround fixing shitty code one line above.

Fix line above and you dont need new line created by @buumi 

https://springrts.com/wiki/Lua_MathExtra or make own rounding function

**Comment by PepeAmpere** [comment]
isn't better

```
local roundsPerTick = math.round(maxAmmo * RELOAD_FREQUENCY / RELOAD_AVERAGE_DURATION)
```

in case of zero value, you have still fallback in code below

**Comment by sanguinariojoe** [comment]
I would prefer not mixing things... This PR is intended to fix #308, which has nothing to do with the math.floor(... + 0.5) trick

**Comment by PepeAmpere** [comment]
I'm not mixing things. The code is unclear and the logic is unnecessary hidden.

Fact is I read the code wrong, I apologize for that, I thought code created by @buumi is doing something else, which is covered already in other code below. 

Still our "fix" is as good as it could be.

E.g. in case you would like to prevent adding resources in case of consuming more resources that we have, there are still 2 better ways to do that:

1) using return value Spring.UseUnitResource(...) https://springrts.com/wiki/Lua_SyncedCtrl#Unit_Resourcing to check if the consumption of resource have succeeded (and update of ammo custom variable will be based on that)
2) use explicit variable saying how much "energy" we would like to consume and then use proper (from clarity perspective) condition comparing "ammo we want to use" (ammoPerTick) <= "ammo we have" (logisticsLevel) - because thats the real meaning of the logic we would like to implement.

I'm not against using `min` function in clear contexts, thats usual practice. It should used as shortcut for `if` statement using smaller of two numbers (representing some units) implicitly doing nothing if value is zero, but not shortcut for comparing numbers (in meaning "make check in other units to decide if we sub-duct something or not"). This goes against balance of the complexity of all lines of code (compare to some lines above and complexity of some if-else statements).

**Comment by PepeAmpere** [comment]
Also what about this:

```
                 if roundsPerTick == 0 then
                     roundsPerTick = 1
                 end
```

shall we have `roundsPerTick = 1` if there is not enough ammo for that?

**Comment by sanguinariojoe** [comment]
Way 1 (so-called EAFTP) can be in fact a smart solution:

```
	if oldAmmo < maxAmmo and weaponCost >= 0 then
                -- scale the number of loaded rounds per tick so that total reload time 
                -- never takes much more than RELOAD_AVERAGE_DURATION
                -- (math.floor + 0.5 trick is because Lua lacks math.round, and we need integers)
                local roundsPerTick = math.floor(maxAmmo * RELOAD_FREQUENCY / RELOAD_AVERAGE_DURATION + 0.5)

                if roundsPerTick == 0 then
                    roundsPerTick = 1
                end

		if UseUnitResource(unitID, "e", weaponCost * roundsPerTick) then
			local newAmmo = oldAmmo + roundsPerTick
			vehicles[unitID].ammoLevel = newAmmo
			SetUnitRulesParam(unitID, "ammo", newAmmo)
		end
	end
```

**Comment by sanguinariojoe** [comment]
> shall we have `roundsPerTick = 1` if there is not enough ammo for that?

Yes, we have. `roundsPerTick = 0` has no sense

**Comment by buumi** [comment]
Well, the fix is now more verbose which hopefully improves the clarity. Hopefully it did not break anything new then. I like the readability viewpoint but originally I wanted to make minimal change to minimize risks. 

Also, as @sanguinariojoe mentioned above option 1. has its issues too. Actually overall, the whole function is too long and could be improved (and let me not get into indentation matter .. seems like tabs and spaces are mixed on per line basis..) Anyways, I let pepe accept this if he feels so. Also joe can say if new version is not ok, in that case i will throw a coin or wait for @ someone to refactor it properly. :P

**Comment by PepeAmpere** [comment]
👍

**Comment by sanguinariojoe** [comment]
TY!

**Pull request merged**
