### PR TITLE
Fixed factories morph

### PR DESCRIPTION
**Pull request by sanguinariojoe**
Factories are not recycling ID... I don't know about eventual side effects...

### CODE REVIEW

**Comment by PepeAmpere** [comment]
❌ sadly this has important consequences to any serious or reasonable AI development (already) and also complicates to extensibility of the game in general - in case all other gadgets and widgets can assume your factories maintain their ID even after morphing, it simplifies (make much cheaper, less time consuming) their development.

Please fix the problem properly or let me do that instead. It took me quite a lot effort to garantuee that on previous version.

**Comment by sanguinariojoe** [comment]
Very poor arguments IMO. If an AI, widget  or gadget is assuming the factory is not changing ID then they would fail in a close future, since the factory is actually not the same. So they shall check the factory definition to track changes, a much more expensive operation indeed, and a much more complex logic...

Anyway, I'm agree that potentially getting unknown collateral damage is not good at all. I think I can manage to get a better logic to recycle the ID. News soon...

**Comment by PepeAmpere** [comment]
@sanguinariojoe why it is poor argument?

current situation:
• unit on given position has unique ID all the time (so all systems based on event handlers working with unitID will work correctly)
• in case the "type" of unit matters (unitDefID) you can handle the morph event (create new event handler in morph gadget or just check "create unit" event)

its significantly less complex and quite reliable system compared the one where unique ID for physical "world entity" (its unique name) is not maintained
• you forced to use unitID everywhere in Spring API, so every part of any system using unitID as input: commands, event handlers, Spring Getters/Setters, any custom system representing any relation between units - need to have extra functionality to handle this

**Comment by sanguinariojoe** [comment]
It does not matters too much, since I'm trying to implement a new logic. But just to feed a bit the discussion:

We are not recycling the unitID of Factories... Just Factories... The unit definition is almost the very only thing a factory has... And if you are using a UnitCreated listener, then who cares about preserving unitID?

I cannot see much situations involving a factory where keeping the unitID would represent an actual benefit. That's why I consider the arguments very poor... Nothing else...

Anyway, I'm testing new logics right now. Hopefully I'm finding a workaround soon to grant backward compatibility!

**Comment by sanguinariojoe** [comment]
Et voilà!

**Comment by sanguinariojoe** [comment]
Apparently @specing has tested the game without this patch in the last 104-maintenance engine, and morph is still broken...

Can you confirm @specing ?

In such case... Is it time to merge? Or we are still stuck with the release?

**Comment by specing** [comment]
That is correct, builder morph is still broken. Would it be possible to move FinishMorph back to its place? Makes git blame harder...

**Comment by sanguinariojoe** [comment]
Done

**Comment by yuritch** [comment]
Seems better compared to my workaround. Let's merge and see how it works.

**Pull request merged**
