### PR TITLE
Improved the faction picker style

### PR DESCRIPTION
**Pull request by sanguinariojoe**
I improved a bit the faction picker widget. You can get a snapshot here:

http://pasteboard.co/5InWcw2Dk.png

---

* You can set the best default location changing `px, py` in line 18 (right now it overlaps with the players list, even though it can be dragged away)
* I added some shitty texts that you would edit

### CODE REVIEW

**Comment by ashdnazg** [comment]
Maybe put random in the middle?

Also I think a "?" icon may be better understood

**Comment by sanguinariojoe** [comment]
I already though about placing random in mid. Let's see what the people says

**Comment by specing** [comment]
I'm still heavily in favor of the thing being centered around the placement market => there cannot be anything in the center. Plus instead of a full circle it would imo be better to have a 2D torus background.
In the future I would like to expand this picker with "focuses" to improve teamwork: e.g. a player with infantry focus would get 20% cheaper infantry in exchange for everything else having a +10% cost bump.

**Comment by ashdnazg** [comment]
Focuses encourage stagnation and increase the RPS. 
It's much better when players can able to react and change unit composition and factories according to the enemy's choices.

**Comment by specing** [comment]
RPS = requests per second? Right now it seems that team games are often multiple parallel 1v1s and something needs to be done to increase teamwork.

Yes, it would. But it can always be changed to some more appropriate form.

**Comment by ashdnazg** [comment]
Rock Paper Scissors.
If you want to increase teamwork:
1) Make some units faster - allow players to shift effort between fronts.
2) Pick/make maps that reward switching fronts

**Comment by ashdnazg** [comment]
> Yes, it would. But it can always be changed to some more appropriate form.

Such as?

**Comment by specing** [comment]
1. I don't fancy making the game more fast paced.
2. Or maps with a single choke point (e.g. deserted gully porcfest), so everyone is focused into the same area => more teamwork.

I don't know, we'll discover along the way.

**Comment by buumi** [comment]
It looks very nice. I also like it this way instead of around marker. This way it's easy to notice. Not sure about centering Random but question mark for it would probably make more sense.

Also not really related to this change but I was never fan of focuses. In addition to ones hoko mentioned it also makes game even harder to balance as changed stats of units can be considered as different units needing to be balanced.

**Comment by sanguinariojoe** [comment]
I'm not very fund on placing it around the marker neither, so...
+1 (@specing)
-3 (@ashdnazg @sanguinariojoe @buumi)
= Rejected (let's see if some other people cast their votes)

Regarding placing random at mid:
+2 (@ashdnazg @sanguinariojoe)
-2 (@specing @buumi)
Another eventual alternative is letting the random marker in the "torus", but replacing the text by something like score bars (e.g. Terrain, Sea, Air)

**Comment by frju365** [comment]
For me, i thought of making a circle (like this) on the place where the player will be in order to see the other faction of his allies. You need to add a sort of previous image of the first building where it will be.
For random i the mid or not, for me it's the same.

**Comment by ashdnazg** [comment]
in order to see allies faction, I can think of two options:
1) draw only that faction's icon above their markers.
2) some highlight or the name of that player near that faction's icon in the widget

**Comment by sanguinariojoe** [comment]
Adding the faction picture on each marker is the next step.

Regarding placing random at mid, since Buumi says he is +0:
+2 (@ashdnazg @sanguinariojoe)
-1 (@specing)
+0 (@frju365 @buumi)
So it is accepted! I'll remove the text and place the random at mid

**Comment by frju365** [comment]
what we could do, is an image of a map (Axis and Ally represented), where the player can click on the country of his faction.  (it's perhaps a bit too much... but I think it's good too). This idea is not to change the faction but only for the first choice(when the player joins the game). Then we had the circle with the faction if the player want to change his faction before the game begins.

I had another idea too : on the circle we can add little circle which represent the other ally in the team(with the color of the player).

**Comment by sanguinariojoe** [comment]
For the time being, I'm placing random at mid (and removing text). I'm also adding the "faction markers"

**Comment by sanguinariojoe** [comment]
Well... Here we go!

http://pasteboard.co/6TlUImaDk.png

New features:

* Removed text from mid
* Moved random to mid
* Now neutral teams are always placed on top
* Added the "faction marker"

I guess it's time to merge before considering further changes

**Comment by frju365** [comment]
That's very good ! +1 :)

**Pull request merged**
